### ISSUE TITLE
Migration of private service config from YAML to PHP

### ISSUE THREAD

**Issue by TavoNiievez** [migrify/config-transformer#3]
given the following config in `'services.yaml'`:
```
services:
    _defaults:
        public: false
```
running `vendor/bin/config-transformer switch-format config/services.yaml --intput-format yaml --output-format php --target-symfony-version 5.1` results in:
```
    $services->defaults()
        ->public(false)
```
but the expected behavior is:
```
    $services->defaults()
        ->private()
```

**Comment by TavoNiievez** [comment]
sorry i'll send it to the proper repository

**Comment by TomasVotruba** [comment]
Thank you
